sonar.projectKey=cyborg-nomade_kantbot
sonar.organization=cyborg-nomade

sonar.projectName=kantbot
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests,typechecks
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
