"""Canonical semantic values for the Kantbot cognitive model.

The package follows the cognitive path in small modules.  Classes are immutable
value objects; later cognitive operations should be pure functions that accept
these values and return new ones.
"""

from kantbot.model.common import (
    CognitiveGround,
    Condition,
    ConditionResult,
    ConditionStatus,
    ConfigurationIdentity,
    ContentField,
    Derivation,
    EvaluatorReference,
    Form,
    FormKind,
    GroundKind,
    RuleAuthority,
    Scope,
    SemanticModel,
)
from kantbot.model.concepts import (
    ApplicationResult,
    ApplicationStatus,
    Concept,
    ConceptKind,
    Schema,
)
from kantbot.model.judgments import (
    AssembledWarrant,
    CommittedJudgment,
    CompleteWarrant,
    Modality,
    ProposedJudgment,
    Proposition,
    UnityCheck,
)
from kantbot.model.outcomes import (
    ApplicationUnderdetermined,
    AuthorityViolation,
    ConceptNotApplicable,
    InputError,
    JudgmentCommitted,
    JudgmentWithheld,
    LimitReport,
    NotPresentable,
    OutcomeContext,
    OutcomeKind,
    Overreach,
    SynthesisAmbiguous,
    SynthesisFailed,
    TerminalOutcome,
    UnityConflict,
    dump_terminal_outcome,
    validate_terminal_outcome,
    validate_terminal_outcome_json,
)
from kantbot.model.procedures import (
    FieldConstant,
    FieldEquals,
    FieldProjection,
    SensibleProcedure,
    StrictIncrease,
    TemporalOrder,
)
from kantbot.model.reason import Reason, ReasonStatus
from kantbot.model.reception import (
    Intuition,
    ManifoldOfIntuition,
    Observation,
    ObservationQuality,
    PresentedElement,
    VariantProjection,
)
from kantbot.model.rules import Rule, RuleKind
from kantbot.model.synthesis import (
    CandidateRepresentation,
    ObjectCandidate,
    RetainedIntuition,
    RetainedSequence,
    RetentionStatus,
    SynthesisPolicy,
)

__all__ = [
    "ApplicationResult",
    "ApplicationStatus",
    "ApplicationUnderdetermined",
    "AssembledWarrant",
    "AuthorityViolation",
    "CandidateRepresentation",
    "CognitiveGround",
    "CommittedJudgment",
    "CompleteWarrant",
    "Concept",
    "ConceptKind",
    "ConceptNotApplicable",
    "Condition",
    "ConditionResult",
    "ConditionStatus",
    "ConfigurationIdentity",
    "ContentField",
    "Derivation",
    "EvaluatorReference",
    "FieldConstant",
    "FieldEquals",
    "FieldProjection",
    "Form",
    "FormKind",
    "GroundKind",
    "InputError",
    "Intuition",
    "JudgmentCommitted",
    "JudgmentWithheld",
    "LimitReport",
    "ManifoldOfIntuition",
    "Modality",
    "NotPresentable",
    "ObjectCandidate",
    "Observation",
    "ObservationQuality",
    "OutcomeContext",
    "OutcomeKind",
    "Overreach",
    "PresentedElement",
    "ProposedJudgment",
    "Proposition",
    "Reason",
    "ReasonStatus",
    "RetainedIntuition",
    "RetainedSequence",
    "RetentionStatus",
    "Rule",
    "RuleAuthority",
    "RuleKind",
    "Schema",
    "Scope",
    "SemanticModel",
    "SensibleProcedure",
    "StrictIncrease",
    "SynthesisAmbiguous",
    "SynthesisFailed",
    "SynthesisPolicy",
    "TemporalOrder",
    "TerminalOutcome",
    "UnityCheck",
    "UnityConflict",
    "VariantProjection",
    "dump_terminal_outcome",
    "validate_terminal_outcome",
    "validate_terminal_outcome_json",
]
